### PR TITLE
Use all connections in pool when executing direct queries

### LINKED ISSUE #164: queryWithParams can not use all connection in the pool
### Version

* vert.x core: `3.7.1`
* vert.x jdbc-client: `3.7.1`
* jdbc driver: `6.0.6`
* RDBMS: `mysql server`

### General info

* What is your jdbc driver: `mysql-connector-java`
* What is your RDBMS server: `mysql`
* What is your connection string (no user/passwords please!): j`dbc:mysql://127.0.0.1:3306/db _dev?autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC`

### Context

I execute a query to the db, and there is two different way that i use jdbc-client and produce two performance result that should be the same.

- create pool
```java
HikariConfig config = new HikariConfig();
    config.setDriverClassName(mySQLConfig.getDriver());
    config.setJdbcUrl(mySQLConfig.getUrl());
    config.setUsername(mySQLConfig.getUser());
    config.setPassword(mySQLConfig.getPassword());
    config.setMaximumPoolSize(mySQLConfig.getPoolSize());
    config.setAutoCommit(isAutoCommit);
    config.addDataSourceProperty("useServerPrepStmts", "" + mySQLConfig.isUseServerPrepStmts());
    config.addDataSourceProperty("cachePrepStmts", "" + mySQLConfig.isCachePrepStmts());
    config.addDataSourceProperty("prepStmtCacheSize", "" + mySQLConfig.getPrepStmtCacheSize());
    config.addDataSourceProperty(
        "prepStmtCacheSqlLimit", "" + mySQLConfig.getPrepStmtCacheSqlLimit());
    config.addDataSourceProperty("maxLifetime", "" + mySQLConfig.getMaxLifetimeMillis());

    try {
      logger.info("Connecting to datasource={}", JsonProtoUtils.printGson(mySQLConfig));
      DataSource dataSource = new HikariDataSource(config);

      mySQLClient = JDBCClient.create(vertx, dataSource);
      if (mySQLClient == null) {
        throw new Exception("mySQLClient == null");
      }
    } catch (Exception e) {
      future.fail(e);
      return future;
    }
```

- method 1: query using getConnection
```java
mySQLClient.getConnection(
          resConnection -> {
            if (resConnection.failed()) {
              result.fail(resConnection.cause());
              return;
            }

            SQLConnection connection = resConnection.result();
            connection.queryWithParams(
                prepareStm,
                params,
                selectRes -> {
                  if (selectRes.failed()) {
                    accountFuture.fail(selectRes.cause());
                  } else {
                    getResult(selectRes.result());
                  }
                  connection.close();
                });
          });
```

- method 2: query using SQLClient.queryWithParams
```java
mySQLClient
        .queryWithParams(prepareStm, params, asyncResultHandler);
```
- and there is result of prometheus metric when i run a benchmark, with connection pool config is 20:
  * method 1: vertx_pool_inUse{pool_type="datasource"}: 20
  * method 2: vertx_pool_inUse{pool_type="datasource"}: 1

and of course, method 1 has req/s much higher than method 2.

I see that both methods above use the  same method
```java
// class JDBCClientImpl
public SQLClient getConnection(Handler<AsyncResult<SQLConnection>> handler) {
    Context ctx = this.vertx.getOrCreateContext();
    this.getConnection(ctx, (ar) -> {
      ctx.runOnContext((v) -> {
        handler.handle(ar);
      });
    });
    return this;
  }
```

then why it makes a huge difference?

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #164

Previously, direct queries execution was serialized on the thread that acquires connection.

### CODE REVIEW

**Comment by vietj** [comment]
@tsegismont again, your commit should tell what changed in `executeDirect` otherwise it is not obvious to review.

File: src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java [hunk 1]
```diff
@@ -170,28 +172,28 @@ public JDBCClient queryWithParams(String sql, JsonArray in, Handler<AsyncResult<
...
+              conn.conn.close();
+            } catch (Exception e) {
+              JDBCConnectionImpl.log.error("Failure in closing connection", e);
+            }
           }
-        }
+        }, false, handler);
       } else {
-        promise.fail(ar1.cause());
+        ctx.runOnContext(v -> handler.handle(Future.failedFuture(ar.cause())));
```
Comment (vietj) [inline src/main/java/io/vertx/ext/jdbc/impl/JDBCClientImpl.java:196]: why is run on context needed here ?

**Review by vietj — APPROVED** [review]
LGTM
