### PR TITLE
Address issue #226 - Fix for missing close of connection when query fails

### LINKED ISSUE #226: JDBCPool.query(...).execute() does not return the connection to the pool if the query is failing
### Version

4.2.0

### Context

I encountered an issue with respect to connection pooling when queries are failing. It looks like the connection is not returned to the connection pool in this case. As a result the pool might run out of connections when we have multiple failing queries.
The issue occurs when we are using the `query(...)` and `preparedQuery(...)` methods of `JDBCPool`:
```
  pool
    .query("SELECT FROM WHERE FOO BAR")
    .execute();
```
When executing the same query via the `withConnection(...)` method of `JDBCPool` we do not see such an issue (therefore using `withConnection(...)` instead of executing queries directly is a wokraround for this issue):
```
  pool
    .withConnection(conn -> conn
      .query("SELECT FROM WHERE FOO BAR")
      .execute());
```

### Do you have a reproducer?

I have a fork of the repository with an extended `JDBCPoolTest` containing tests for the issue as well as the workaround (see https://github.com/riemenschneider/vertx-jdbc-client).

### Steps to reproduce

1. Clone the reproducer.
2. Run `io.vertx.jdbcclient.JDBCPoolTest`.

### PR DESCRIPTION
**Pull request by riemenschneider**
This change fixes #226 since the closing of connections for failing queries created by JDBCPool.query(...) or JDBCPool.preparedQuery(...) is currently broken.
Additionally adds according regression tests to JDBCPoolTest.

### CODE REVIEW

**Comment by riemenschneider** [comment]
Unfortunately some tests are failing with the following error
```
java.sql.SQLException: Access is denied: pom.xml
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.SessionData.getFile(Unknown Source)
	at org.hsqldb.SessionData.createBlobFromFile(Unknown Source)
	at org.hsqldb.FunctionCustom.getValue(Unknown Source)
	at org.hsqldb.FunctionSQL.getValue(Unknown Source)
	at org.hsqldb.StatementDML.getInsertData(Unknown Source)
	at org.hsqldb.StatementInsert.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source)
	at io.vertx.ext.jdbc.JDBCClientTestBase.resetDb(JDBCClientTestBase.java:73)
	at io.vertx.jdbcclient.ClientTestBase.setUp(ClientTestBase.java:26)
	at io.vertx.jdbcclient.JDBCPoolCustomTypesTest.setUp(JDBCPoolCustomTypesTest.java:58)
```
which is (to the best of my knowledge) not connected to my fix.

**Comment by vietj** [comment]
this only fails in CI

**Comment by riemenschneider** [comment]
That's correct. Locally all tests are running successful...

**Comment by vietj** [comment]
can you rebase onto latest master ? now CI should work fine.

**Comment by riemenschneider** [comment]
Done

File: src/main/java/io/vertx/jdbcclient/impl/JDBCPoolImpl.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ public void close(Handler<AsyncResult<Void>> handler) {
   @Override
   public <R> Future<R> schedule(ContextInternal contextInternal, CommandBase<R> commandBase) {
     ContextInternal ctx = vertx.getOrCreateContext();
-    return getConnectionInternal(ctx).flatMap(conn -> ((SqlConnectionImpl<?>) conn).schedule(ctx, commandBase).flatMap(r -> conn.close().map(r)));
+    return getConnectionInternal(ctx).flatMap(conn -> ((SqlConnectionImpl<?>) conn).schedule(ctx, commandBase).onFailure(err -> conn.close()).flatMap(r -> conn.close().map(r)));
```
Comment (vietj) [inline src/main/java/io/vertx/jdbcclient/impl/JDBCPoolImpl.java:101]: good catch, there is actually a specific future operation that handle this case that is eventually, so I think we could replace the `flatMap` with `eventually` and then there is no need for `onFailure`

**Comment by riemenschneider** [comment]
Done. Looks much nicer now...

File: src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java [hunk 2]
```diff
@@ -379,4 +380,52 @@ public void testPreparedStatementWithBufferParam(TestContext should) {
         )
       );
   }
+  
+  @Test
+  public void testConnectionReturnedToPoolOnFailingQueryExecution(TestContext should) {
+    final Async test = should.async();
```
Comment (vietj) [inline src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java:386]: how does the test checks that the connection was actually closed ?

Comment (riemenschneider) [reply src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java:386]: The superclass of `JDBCPoolTest` configures are pool with max size 1
https://github.com/vert-x3/vertx-jdbc-client/blob/3561a6fc52189f737d96a5e327c4816af1a464da/src/test/java/io/vertx/jdbcclient/ClientTestBase.java#L36-L38

In the test we are executing two failing queries. 
https://github.com/vert-x3/vertx-jdbc-client/blob/bd6f836c64a3c21207827db28b105a5bff7f081d/src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java#L390-L404
The first one will fail with a `SQLSyntaxErrorException`. If the according connection is closed and returned to the pool, the second query will fail immediately with the same `SQLSyntaxErrorException`. If the according connection is not closed, the pool will be exhausted and we will see an according `SQLException` after acquisition timeout.
```
java.sql.SQLException: Sorry, acquisition timeout!
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:304)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:241)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:81)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.lambda$5(JDBCClientImpl.java:226)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

File: src/main/java/io/vertx/jdbcclient/impl/JDBCPoolImpl.java (hunk 1 above)
Comment (riemenschneider) [reply src/main/java/io/vertx/jdbcclient/impl/JDBCPoolImpl.java]: Done. Looks much nicer now...

File: src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java (hunk 2 above)
Comment (vietj) [reply src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java:386]: thanks, can you add a comment in the test for this ? I think it's worth to be captured.

Comment (riemenschneider) [reply src/test/java/io/vertx/jdbcclient/JDBCPoolTest.java:395]: Done.

**Comment by vietj** [comment]
thanks a lot
