### PR TITLE
fix #253

### LINKED ISSUE #253: JDBCSQLRowStream hangs
### Version

- vertx 3.9.x
- vertx 4.x

### Context

Sometimes `JDBCSQLRowStream` stops unexpectedly.

### Do you have a reproducer?

I cannot reproduce this bug with `AsyncResult` handlers, but it is fairly easy to reproduce with kotlin coroutines.

### Steps to reproduce

Reproducer and fix will be provided shortly

### PR DESCRIPTION
**Pull request by ruslansennov**
#253

### CODE REVIEW

File: src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java [hunk 1]
```diff
@@ -200,7 +200,7 @@ private void empty(Throwable err) {
 
     if (rsClosedHandler != null) {
       // only close the result set and notify
-      close0(c -> {
+      closeRS(pending.isEmpty(), c -> {
```
Comment (ruslansennov) [inline src/main/java/io/vertx/ext/jdbc/impl/actions/JDBCSQLRowStream.java:203]: We should suspend a pending buffer only if it is empty.

**Review by pmlopes — APPROVED** [review]
