### PR TITLE
fixes #16 and #17

### LINKED ISSUE #16: Oracle number type can't checkAndCopy
Dear all,
      Oracle number type at "select" can't checkAndCopy
java.lang.IllegalStateException: Illegal type in JsonObject: class java.math.BigDecimal
	at io.vertx.core.json.Json.checkAndCopy(Json.java:116)
	at io.vertx.core.json.JsonArray.add(JsonArray.java:396)
	at io.vertx.ext.jdbc.impl.actions.AbstractJDBCStatement.asList(AbstractJDBCStatement.java:79)

  protected Object convertSqlValue(Object value) {
    if (value instanceof Date || value instanceof Time || value instanceof Timestamp) {
      return value.toString();
    } else {
      return value;
    }
  }

change

  protected Object convertSqlValue(Object value) {
    if (value instanceof Date || value instanceof Time || value instanceof Timestamp || value instanceof BigDecimal) {
      return value.toString();
    } else {
      return value;
    }
  }

### PR DESCRIPTION
**Pull request by pmlopes**
the conversion from JDBC to JSON types was incomplete, this new implementation fixes the issue and add a second DB test server (derby) that would reproduce the issues #16 and #17.

@purplefox @vietj please review.

Also note that the new implementation handles returned dates (DB -> JSON) in the same format as mongo-client for consistency.

### CODE REVIEW

File: src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCStatement.java [hunk 1]
```diff
@@ -88,10 +95,82 @@ protected void fillStatement(PreparedStatement statement, JsonArray parameters)
...
+    if (value == null) {
+      return null;
+    }
+
+    // valid json types are just returned as is
+    if (value instanceof Boolean || value instanceof String || value instanceof byte[]) {
+      return value;
+    }
+
+    // numeric values
```
Comment (purplefox) [inline src/main/java/io/vertx/ext/jdbc/impl/actions/AbstractJDBCStatement.java]: Do we have corresponding tests for all these types that are now supported?

**Comment by pmlopes** [comment]
extra tests added to show the handling of jdbc blob/clob/array

**Comment by cescoffier** [comment]
Looks ok for me, I just would like to see the current coverage of the tests. I let you know.

**Comment by cescoffier** [comment]
Your tests cover most of the new code. 

It looks like the fallback (toString) is not tested, would probably be a good addition (just to avoid suprise when it crosses the whole method).

Except that everything is fine.
